services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hono-api
    ports:
      - '5000:5000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/hono_db?sslmode=disable
      - ACCESS_TOKEN=your-secret-token-123
    restart: unless-stopped

  drizzle-studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drizzle-studio
    command: pnpm studio
    ports:
      - '4000:4000'
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/hono_db?sslmode=disable
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: hono-drizzle-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hono_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
