services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hono-api
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/hono_db
    restart: unless-stopped

  drizzle-studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drizzle-studio
    command: pnpm studio
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/hono_db
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: hono-drizzle-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hono_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: